# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b226289894469b8badb56a2e7f01ec812ecc9e576173b508cacab0e798f6e4feed6c6ba55f528044070c4af62a87752a3604579974ce775360a6003cebd2c408

test:
  secret_key_base: 6061b26cdf578353222685be1756acef4ab305d21550cf5d06f3c002a8ef405bb8e86773fa43768ca0fad3b27d81a9890efecba7c7bd924cacf0162ff43d1de3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
