# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e89b9eaecf5d6273fb287bdab957d72eee69e2544ecc3242c1f11afb65bc8eb252c365f6805d65009ce8a939858bf100dd8c74f7bc0847a43e8397cf96051cb

test:
  secret_key_base: 98d0e8b3a5c8a518fbbed8a9b10162d6c2ec76bb1505edbef10aff8bb7727a32b0532ba50d8dad82672768a35c022e927d9517574eadb54d49f37e3e786c6c97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
