# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de91b70162d75ce14da6c058be22ad54ce67a1ff33735f7cc1bd7756a91c47894af7ea8e81937de972ae79eff89c68da2a46a1c8af6f75c6e14535e619b12529

test:
  secret_key_base: 3efb473ccc7db571c2733f42344de23f62e156bcf779442e555042b7349d05a05a3f6307ec4435ed9e60d928a8037776807121d49ab0ab90cde20601326e8f28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
